samples/Nix: fix example
A substitution in a substitution is invalid syntax (and not needed) and
therefore breaks evaluation with an error like this on Nix 2.1:

```
error: syntax error, unexpected DOLLAR_CURLY
```